### ISSUE TITLE
TypeError: type NoneType doesn't define __round__ method

### ISSUE THREAD

**Issue by M-Asim-Javed** [ksiewert/BetaScan#28]
Hello,

I am running Betascan for 20 chromosomes without outgroup information. While running it with all chromosomes, an error pops up (below here), but it computes the values when run with individual chromosomes separately and generates Beta* values for each chromosome. Is it normal to use individual chromosomes to calculate Beta*? Could you help me with this? 

I would greatly appreciate it.

Here's the command I used for Betascan:

`````
python BetaScan.py -i transformed_PL.beta.txt -fold -w  2000 -o betascan_output/pb_betascores_transformed.txt

`````

## Error 

Traceback (most recent call last):
  File "/home/edelab/asim_work/vcf_analysis/files_for_vcf/gdgeno_snps_data/nucleotide_diversity/tajimaD/vcftools_new/vcftools/betascan/BetaScan.py", line 685, in <module>
    main()
  File "/home/edelab/asim_work/vcf_analysis/files_for_vcf/gdgeno_snps_data/nucleotide_diversity/tajimaD/vcftools_new/vcftools/betascan/BetaScan.py", line 673, in main
    output.write(str(loc)+"\t"+str(round(B, 6))+"\n")  # Remove thetas
                                   ^^^^^^^^^^^
TypeError: type NoneType doesn't define __round__ method

**Comment by ksiewert** [comment]
Hi Muhammad, BetaScan is only meant to be run on one chromosome at a time.
